with open('scripts/debug-dirty-state.mjs', 'w') as f:  
    dq = chr(34)  
    bt = chr(96)  
    nl = chr(10)  
    lines = []  
    lines.append('import { chromium } from ' + dq + 'playwright' + dq + ';')  
    lines.append('import path from ' + dq + 'path' + dq + ';')  
    lines.append('')  
    lines.append('const QA_URL = ' + dq + 'https://onya-qa-api-gwkke6nq5a-el.a.run.app' + dq + ';')  
    lines.append('const ADMIN_HOME = ' + bt + '{QA_URL}/admin/home' + bt + ';') 
    lines.append('const SCREENSHOTS_DIR = path.join(process.cwd(), ' + dq + 'scripts' + dq + ', ' + dq + 'c08b-06-screenshots' + dq + ');')  
    lines.append('')  
    lines.append('async function run() {')  
    lines.append('  const browser = await chromium.launch({ headless: true });')  
    lines.append('  const context = await browser.newContext();')  
    lines.append('  const page = await context.newPage();')  
    lines.append('')  
    lines.append('  console.log(' + dq + 'Navigating to admin home...' + dq + ');')  
    lines.append('  await page.goto(ADMIN_HOME, { waitUntil: ' + dq + 'networkidle' + dq + ' });')  
    lines.append('  ')  
    lines.append('  if (page.url().includes(' + dq + '/admin/login' + dq + ')) {')  
    lines.append('    await page.fill(' + dq + 'input[name=email]' + dq + ', ' + dq + '0@0nya.com' + dq + ');')  
    lines.append('    await page.fill(' + dq + 'input[name=password]' + dq + ', ' + dq + 'Nile-Quartz-74!mR9' + dq + ');')  
    lines.append('    await page.click(' + dq + 'button[type=submit]' + dq + ');')  
    lines.append('    await page.waitForTimeout(3000);')  
    lines.append('  }') 
    lines.append('')  
    lines.append('  console.log(' + dq + 'Current URL:' + dq + ', page.url());')  
    lines.append('')  
    lines.append('  const firstRowHeader = page.locator(' + dq + 'article button[aria-expanded]' + dq + ').first();')  
    lines.append('  await firstRowHeader.click();')  
    lines.append('  await page.waitForTimeout(500);')  
    lines.append('  ')  
    lines.append('  const initialDirty = await page.evaluate(() => {')  
    lines.append('    const articles = document.querySelectorAll(' + dq + 'article' + dq + ');')  
    lines.append('    const results = [];')  
    lines.append('    articles.forEach((article, i) => {')  
    lines.append('      const headerBtn = article.querySelector(' + dq + 'button[aria-expanded]' + dq + ');')  
